import type { Workflow, ChecklistItem } from '../types/workflow';
import type { Service } from '../types/service';
import { mockWorkflows, mockServices } from '../data/mockWorkflows';
import { apiGet, apiPost } from './http';

// In-memory copy of the seed workflows (checklist toggles kept stateful).
let currentWorkflows: Workflow[] = [...mockWorkflows];
// Workflows generated by the backend through POST /api/ask, cached locally so
// pages can toggle their checklists without a round-trip.
let generatedWorkflows: Workflow[] = [];

function allWorkflows(): Workflow[] {
  return [...currentWorkflows, ...generatedWorkflows];
}

function cacheGenerated(workflow: Workflow): void {
  generatedWorkflows = [
    ...generatedWorkflows.filter(w => w.id !== workflow.id),
    workflow,
  ];
}

function toggleIn(workflow: Workflow, itemId: string): Workflow {
  const updatedChecklist: ChecklistItem[] = workflow.checklist.map(item =>
    item.id === itemId ? { ...item, completed: !item.completed } : item,
  );
  const completedCount = updatedChecklist.filter(i => i.completed).length;
  const readiness = Math.round((completedCount / updatedChecklist.length) * 100);
  const nextItem = updatedChecklist.find(i => !i.completed);

  return {
    ...workflow,
    checklist: updatedChecklist,
    readiness,
    nextUp: nextItem?.title,
    status: readiness === 100 ? 'Completed' : readiness > 0 ? 'In Progress' : 'Action Needed',
  };
}

export const workflowService = {
  async getWorkflows(): Promise<Workflow[]> {
    const local = allWorkflows();
    try {
      // Merge backend-generated workflows with the local set. Local state
      // (mocks + anything already cached this session, incl. checklist
      // toggles) wins for ids we know; the backend fills in generated flows
      // that aren't cached yet (e.g. after a page refresh). The merge is
      // recomputed from scratch so concurrent calls (React StrictMode double
      // effects) can never duplicate entries.
      const backend = await apiGet<Workflow[]>('/api/workflows');
      const byId = new Map<string, Workflow>();
      for (const w of local) byId.set(w.id, w);
      for (const b of backend) {
        if (!byId.has(b.id)) byId.set(b.id, b);
      }
      const merged = [...byId.values()];
      const mockIds = new Set(currentWorkflows.map(w => w.id));
      generatedWorkflows = merged.filter(w => !mockIds.has(w.id));
      return merged;
    } catch {
      return local;
    }
  },

  async getWorkflowById(id: string): Promise<Workflow | undefined> {
    // 1) Cached copy covers the 3 mock workflows and any generated workflow
    //    already fetched this session.
    const cached = allWorkflows().find(w => w.id === id);
    if (cached) return cached;

    // 2) Fall back to the backend store so a generated workflow stays
    //    reachable (e.g. after navigating away or refreshing the page) for as
    //    long as the backend process is running.
    try {
      const fetched = await apiGet<Workflow>(`/api/workflows/${id}`);
      cacheGenerated(fetched);
      return fetched;
    } catch {
      return undefined;
    }
  },

  async toggleChecklistItem(workflowId: string, itemId: string): Promise<Workflow> {
    const target = allWorkflows().find(w => w.id === workflowId);
    if (!target) throw new Error('Workflow not found');
    const updated = toggleIn(target, itemId);

    if (currentWorkflows.some(w => w.id === workflowId)) {
      currentWorkflows = currentWorkflows.map(w => (w.id === workflowId ? updated : w));
    } else {
      generatedWorkflows = generatedWorkflows.map(w => (w.id === workflowId ? updated : w));
    }
    return updated;
  },

  async ask(query: string): Promise<Workflow> {
    // Single data-access path: Ask.tsx -> this -> http.ts -> FastAPI -> Gemini.
    const workflow = await apiPost<Workflow>('/api/ask', { query });
    cacheGenerated(workflow);
    return workflow;
  },

  async getServices(): Promise<Service[]> {
    return Promise.resolve(mockServices);
  },

  async getServiceByName(name: string): Promise<Service | undefined> {
    // Normalize both sides so canonical names from generated workflows
    // ("Google Drive") resolve to the seeded service ("Drive").
    const normalize = (value: string) =>
      value.toLowerCase().replace(/^google\s+/, '').replace(/\s+/g, ' ').trim();
    return Promise.resolve(
      mockServices.find(s => normalize(s.name) === normalize(name)),
    );
  },
};
